### ISSUE TITLE
Feature Request: Firing on state change to any state

### ISSUE THREAD

**Issue by DKBBhavya** [skydo-tech/hibernate-fsm#6]
Edited

Expected Behaviour:
I have a generic function which needs to be executed whenever a successful state change happens, irrespective of initial and final value. I want a feature which can provide a way to execute the function without writing a boiler plate for every state change

**Comment by r1jsheth** [comment]
Description is a bit unclear, please provide a proper example as well.

**Comment by DKBBhavya** [comment]
> Description is a bit unclear, please provide a proper example as well.

Edited Description

**Comment by r1jsheth** [comment]
sounds like a good idea, see if you can pick this up.

**Comment by r1jsheth** [comment]
Wonderful work! @DKBBhavya
